.prettierrc
eslint.config.mjs
package-lock.json
package.json

- close #123 
프리티어 적용
```
{
"printWidth": 80, // 한 줄 최대 길이 100자
"endOfLine": "auto", // 운영체제에 따라 줄바꿈 자동 조정
"tabWidth": 2, // 탭 간격 2칸
"useTabs": false, // 스페이스(공백) 사용 (탭 대신)
"semi": true, // 세미콜론(;) 강제 추가
"singleQuote": true, // 문자열을 싱글쿼트(')로 사용
"quoteProps": "as-needed", // 필요한 경우에만 객체 속성에 따옴표 사용
"trailingComma": "all", // 모든 리스트 마지막에도 콤마(,) 추가
"bracketSpacing": true, // { key: value } 형태로 공백 추가
"jsxSingleQuote": true, // JSX에서 싱글쿼트(') 사용
"bracketSameLine": false, // JSX 태그의 >를 다음 줄로 이동
"arrowParens": "always", // 화살표 함수의 매개변수에 항상 괄호 사용
"parser": "typescript", // TypeScript 코드 자동 분석
}
```

Chore(#123): 프리티어 적용

---

src/styles/globals.css

- close #139 
footer globalCSS 추가수정

Chore(#139): footer globalCSS 추가 수정

---

src/components/Dropdown.tsx
src/components/nav/Nav.tsx
src/utils/useClickOutside.ts

- close #이슈번호X
Dropdown, Nav-ProfileCard 영역 외 클릭 시 닫기 관련 코드 및 이벤트 유틸리티 함수로 변경 & 일괄 적용

Refector(#이슈번호X): Dropdown, Nav-ProfileCard 영역 외 클릭 시 닫기 관련 코드 및 이벤트 유틸리티 함수로 변경 & 일괄 적용

---

src/components/empty/Empty.tsx
src/components/empty/empty.module.css

- close #이슈번호X
- 데이터 내역 빈페이지 코드 간결화
- features 브랜치에 수정 코드 업뎃 되면 혜연님과 보배님께 전달 예정입니다.

Chore(#이슈번호X): 데이터 내역 빈페이지 코드 간결화

---

src/app/myReservation/page.tsx
src/app/mynotification/page.tsx
src/components/Dropdown.tsx
src/lib/api.ts

- close #69 
- 내가 등록한 체험 없는 경우 빈 페이지 렌더링

feat(#69): 내 체험예약 빈페이지 

---

src/app/mynotification/MyNotification.module.css
src/app/mynotification/components/Calendar.module.css
src/app/mynotification/components/Calendar.tsx
src/app/mynotification/page.tsx
src/lib/api.ts

- close #이슈번호X
- 자잘한 오류사항 수정 및 미디어쿼리 적용

chore: mynoti media query

---

.github/workflows/vercel.yml

vercel/배포 v1.yml

---

src/app/(auth)/signup/components/SignUpForm.module.css
src/app/(auth)/signup/components/SignUpForm.tsx
src/app/test/namgyeon/page.tsx
src/components/Input/Input.module.css
src/components/Input/Input.tsx
src/components/Input/PasswordInput.tsx

- close #161 
- input 에러시 css추가
- PasswordInput props(label,id)추가
물

Fix(#161): input 에러시 css추가, PasswordInput props(label,id)추가

---

package-lock.json

- close #이슈번호X
package-lock.json 컨플릭트 해결 (features 기준)

Fix(#이슈번호X): package-lock.json 컨플릭트 해결 (features 기준)

---

src/app/test/namgyeon/page.tsx
src/components/Input/DateInput.tsx
src/components/Input/Input.tsx
src/components/Input/SelectInput.tsx

- close #191
- DateInput: ref를 리액트19버전에 맞게 수정.
- Input: props을 유연하게 확장하기위해 ComponentProps<'input'> 활용해서 수정.
- Input: props의 labelSize를 boolean타입으로 변경.
- SelectInput: 상태값을 부모에게도 넘겨주기 위해서 props설정.
- 사용하다가 문제 있으면 말해주세요 바로 수정할 수 있도록 하겠습니다!

fix(#191): input 공용 컴포넌트 수정

---

src/components/Input/Input.tsx

- close #204 
-input :  스타일 조정할 수있는 props 추가

feat(#204):스타일 조정할 수있는 props 추가

---

src/components/nav/Nav.tsx
src/components/nav/NavProfileCard.tsx
src/components/nav/nav.module.css

- close #172 
- 로그인 시 네비게이션 유저 데이터 연동
- 네비게이션의 Notification 모달 position 위치 조정이 필요해 보입니다.

Feat(#172): 로그인 시 네비게이션 유저 데이터 연동

---

src/components/nav/Nav.tsx
src/components/notification/NotificationModal.module.css

- close #이슈번호X
- 네비게이션 알림 모달 위치 조정
- Nav.tsx 의 html 구조 변경과 NotificationModal.module.css 수정이 있었습니다.

Fix(X): 네비게이션 알림 모달 위치 조정

---

src/app/mypage/components/ProfileUpdateModal.tsx

Chore(#245): 빌드

---

src/app/mynotification/MyNotification.module.css
src/app/mynotification/components/ReservationInfoModal.module.css
src/app/mynotification/components/ReservationInfoModal.tsx
src/lib/api.ts

Chore: 내 체험 예약 디자인 수정

---

src/app/myReservation/components/ReservationItem.tsx
src/app/myReservation/components/WriteReviewModal.tsx
src/components/modal/customModal.module.css
src/components/nav/NavProfileCard.tsx
src/utils/formattedDate.tsx
src/utils/useScrollPositioning.ts

- close #이슈번호X
- 누락된 빌드 에러 수정 및 코드 정리

Fix(#이슈번호X): 빌드 에러 수정 및 코드 정리

---

src/app/myReservation/components/WriteReviewModal.tsx
src/components/modal/customModal.module.css
src/components/rating/StarRating.tsx

- close #52, #55 
- 별점 기본값은 1이며, 후기 value 값이 존재할 때 작성 버튼을 활성화 처리 했음

Feat(#52, 55): 별점 및 후기 value 값에 따른 작성 버튼 활성화 처리

---

src/app/landingComponents/Search.module.css
src/app/landingComponents/Search.tsx
src/app/myReservation/page.tsx
src/app/mypage/components/ProfileUpdateModal.tsx
src/components/ProfileCard/ProfileCard.tsx
src/lib/api.ts

- close #220 #57 
- 프로필 변경 값 중 하나만 변경해도 그대로 업데이트
- 비밀번호는 더미 텍스트로 대체

feat(#220): 프로필 변경 값 하나만 해도 업데이트

---

src/app/myReservation/components/ReservationItem.tsx
src/app/myReservation/components/ReservationList.tsx
src/app/myReservation/components/WriteReviewModal.tsx
src/app/myReservation/style.module.css
src/components/modal/ModalType1.tsx
src/hooks/useWriteReview.ts

- close #46 #56 
- 후기 등록 api 전송
- 후기 등록 완료 > '후기 작성' 버튼 비활성화 및 '후기 작성 완료' 텍스트 출력 & 토스트 출력
- 담당 작업 모두 완료됐습니다. 테스트 진행하면서 추가적으로 보완 할 버그들 찾아서 마무리 작업 진행 하겠습니다.

Feat(#46, 56): 체험 후기 등록 api 전송

---

.gitignore
src/app/myReservation/components/CancelModal.tsx
src/app/myReservation/components/ReservationItem.tsx
src/app/myReservation/components/WriteReviewModal.tsx
src/app/not-found.tsx
src/components/modal/ModalType2.tsx
src/components/modal/customModal.module.css
src/utils/formattedDate.tsx
src/utils/useStatusFilter.ts

- close #이슈번호X
1. useStatusFilter.ts에서 useEffect를 제거하고 대체 코드로 보완해보았습니다.
2. CustomButton 공통 컴포넌트 활용 시 개별적으로 사용했던 CSSProperties를 제거하고 최대한 공통 컴포넌트에서 제공하는 프로퍼티를 사용했습니다. 이미 프로젝트가 많이 진행된 상태라 담당자분과 협의하에 공통 컴포넌트의 기존 CSS를 변경하기보다는, 추가적으로 필요한 CSS가 많지 않아 style 프로퍼티를 이용해 적용해두었습니다.
3. .gitignore 파일명 대소문자 변경 옵션 추가를 했지만 로컬에서는 이미 변경된 디렉토리명을 사용하고 있기 때문에 반영이 잘 될 지는 테스트를 거쳐봐야 할 것 같습니다.
4. formattedDate.tsx의 함수명이 대문자로 시작하여 소문자로 수정하였습니다.

Refactor(#X): 멘토링 시간 언급된 내용들을 위주로 수정

---

src/app/test/namgyeon/page.tsx
src/components/Input/Input.tsx

- close #285 
- 어색한 prop의 이름을 변경했습니다. (labelSize -> isLabelLarge)
- input컴포넌트를 활용하시는 분들은 prop의 이름을 변경해야 합니다!

refactor(#285): input prop labelSize -> isLabelLarge로 변경

---

package-lock.json
src/app/landingComponents/Category.tsx
src/app/page.tsx

- 
- 카테고리, 드롭다운 옵션 별로 클릭시 첫 페이지로 이동
- 랜딩페이지에서 api데이터 패칭 useEffect -> React Query로 변경

feat: 데이터 패칭 React Query로 변경

---

src/components/modal/ModalType1.tsx

fix: import file 이름 수정

---

public/images/close_modal.svg
src/app/myreservation/components/CancelModal.tsx
src/app/myreservation/components/ReservationItem.tsx
src/app/myreservation/components/ReservationList.tsx
src/app/myreservation/components/WriteReviewModal.tsx
src/app/myreservation/style.module.css
src/app/not-found.tsx
src/components/modal/ModalType1.tsx
src/components/modal/ModalType2.tsx
src/components/modal/customModal.module.css
src/components/rating/StarRating.tsx
src/components/rating/rating.module.css
src/hooks/mutation/useUpdateReview.ts
src/hooks/useWriteReview.ts
src/utils/formattedDate.ts
src/utils/formattedDate.tsx
src/utils/useFormatDate.ts
src/utils/useStatusFilter.ts

- close #이슈번호X
- 리뷰 작성 모달 UI/UX
- 리뷰 업데이트 API
- 코드 보완 및 정리

merge: feature/reservation > features

---

next.config.ts
package-lock.json
package.json
src/app/landingComponents/ActivitiesList.tsx
src/app/landingComponents/Category.tsx
src/app/landingComponents/PopularActivities.module.css
src/app/landingComponents/PopulorActivities.tsx

- #226
인기체험 리스트 gap적용안되는 부분 개선해야함

feat(#226): 인기체험 슬라이드 적용

---

src/app/(auth)/oauth/kakao/signin-callback/page.tsx
src/hooks/useAuth.tsx
src/lib/auth-api.ts

- close #325
- useEffect안에 객체가 들어가서 무한 요청되던것을 삭제하여 오류 해결

fix(#325): useEffect무한 요청 버그 수정

---

src/app/activities/[id]/components/ActivityHeader.tsx
src/app/activities/[id]/index.module.css
src/app/activities/[id]/page.tsx

feat: 페이지 헤더 구현

---

src/app/activities/[id]/components/ActivityBody.tsx
src/app/activities/[id]/components/KakaoMap.tsx
src/app/activities/[id]/components/SliderArrow.tsx
src/app/activities/[id]/components/activityBody.module.css
src/app/activities/[id]/components/sliderArrows.module.css

feat: 반응형 배너이미지 및 카카오맵

---

src/app/activities/[id]/components/ActivityReviews.tsx
src/app/utils/dateFormatter.ts

feat: 체험후기 불러오기

---

src/components/nav/Nav.tsx
src/components/nav/NavProfileCard.tsx
src/hooks/query/useUser.tsx

- close #이슈번호X
- 네비게이션 유저 정보 실시간 수정 안되는 버그 수정 코드 재업데이트 합니다.

fix(X): 네비게이션 유저 정보 실시간 수정 안되는 버그 재업데이트

---

src/app/activities/[id]/components/ActivityBody.tsx
src/app/activities/[id]/components/ActivityReviews.tsx
src/app/activities/[id]/components/CalendarModal.module.css
src/app/activities/[id]/components/ReservationCard.tsx
src/app/activities/[id]/components/activityBody.module.css
src/app/activities/[id]/components/reservationCard.module.css
src/app/activities/[id]/index.module.css
src/app/activities/[id]/page.tsx
src/components/modal/CustomModal.tsx
src/hooks/query/useActivity.ts
src/hooks/query/useActivityReviews.ts

custom 모달 스크롤 방지 및 css 수정

---

src/app/activities/[id]/components/ReservationCard.tsx

chore: 에러 메시지 수정
